version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgresdb
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  postgresdb:
    image: 'postgres:12'
    hostname: 'distributor'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - distributor-postgres-data:/var/lib/postgresql/data
volumes:
  distributor-postgres-data: