# Generated by Django 4.1.6 on 2023-08-10 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категории:')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=255, verbose_name='Времена')),
            ],
            options={
                'verbose_name': 'Времена',
                'verbose_name_plural': 'Времена',
            },
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Введите идиому:')),
            ],
            options={
                'verbose_name': 'Идиомы',
                'verbose_name_plural': 'Идиомы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Введите слово:')),
                ('image_url', models.URLField(verbose_name='Ссылка на фото:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Введите цитату:')),
            ],
            options={
                'verbose_name': 'Цитаты',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nza.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='фотография пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('statistics', models.TextField(blank=True, verbose_name='Статика')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Введите тему:')),
                ('description', models.TextField(max_length=255, verbose_name='Введите описание темы:')),
                ('test', models.JSONField(blank=True, max_length=255, null=True, verbose_name='Тест:')),
                ('json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('time', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='nza.chapter', verbose_name='Времена')),
            ],
            options={
                'verbose_name': 'Грамматика',
                'verbose_name_plural': 'Грамматика',
            },
        ),
    ]
