# Generated by Django 4.1.6 on 2023-08-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
