# Generated by Django 4.1.6 on 2023-08-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nza.question'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
