# Generated by Django 4.1.6 on 2023-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0002_alter_grammar_test_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='test',
        ),
        migrations.AddField(
            model_name='grammar',
            name='test',
            field=models.ManyToManyField(to='nza.question'),
        ),
    ]
