# Generated by Django 4.1.6 on 2023-07-24 08:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
