# Generated by Django 4.1.6 on 2023-07-24 10:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0003_grammarlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.CharField(max_length=255)),
                ('save', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='GrammarLesson',
        ),
    ]
