# Generated by Django 4.1.6 on 2023-08-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0003_remove_grammar_test_grammar_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Tест', 'verbose_name_plural': 'Тест'},
        ),
    ]
