# Generated by Django 4.1.6 on 2023-08-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0004_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слово'),
        ),
    ]
