# Generated by Django 4.1.6 on 2023-08-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0005_rename_chapter_subsection_subsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
