# Generated by Django 4.1.6 on 2023-07-27 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nza', '0005_rename_save_grammar_json_alter_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='test',
            field=models.JSONField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='фотография пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('statistics', models.TextField(blank=True, verbose_name='Статика')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
