# Generated by Django 4.1.6 on 2023-08-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0005_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nza.category', verbose_name='Категория'),
        ),
    ]
