# Generated by Django 4.1.6 on 2023-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0006_alter_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='test',
            field=models.ManyToManyField(to='nza.question', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default=1, max_length=100, verbose_name='Слово'),
            preserve_default=False,
        ),
    ]
