# Generated by Django 4.1.6 on 2023-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0007_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(max_length=50, verbose_name='Автор:'),
        ),
    ]
