# Generated by Django 4.1.6 on 2023-08-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0007_alter_grammar_test_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(null=True, verbose_name='Ссылка на фото:'),
        ),
    ]
