# Generated by Django 4.1.6 on 2023-08-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0008_alter_photo_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterModelOptions(
            name='antonym',
            options={'verbose_name': 'Антоним', 'verbose_name_plural': 'Антонимы'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Cиноним', 'verbose_name_plural': 'Синонимы'},
        ),
    ]
