# Generated by Django 4.1.6 on 2023-08-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0009_delete_photo_alter_antonym_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
