# Generated by Django 4.1.6 on 2023-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0009_remove_word_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')]),
        ),
    ]
