# Generated by Django 4.1.6 on 2023-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0010_question_answer_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(max_length=100, verbose_name='Ответ 1:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(max_length=100, verbose_name='Ответ 2:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.CharField(max_length=100, verbose_name='Ответ 3:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.CharField(max_length=100, verbose_name='Ответ 4:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], verbose_name='Правильный ответ:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст:'),
        ),
    ]
