# Generated by Django 4.1.6 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0012_alter_listening_options_alter_listening_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
