# Generated by Django 4.1.6 on 2023-09-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('antonym', models.JSONField()),
            ],
            options={
                'verbose_name': 'Антоним',
                'verbose_name_plural': 'Антонимы',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(verbose_name='Пример: ')),
            ],
            options={
                'verbose_name': '7. Пример',
                'verbose_name_plural': '7. Примеры',
            },
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Введите идиому')),
            ],
            options={
                'verbose_name': '4. Идиома',
                'verbose_name_plural': '4. Идиомы',
            },
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': '5. Аудирование',
                'verbose_name_plural': '5. Аудирование',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст:')),
                ('answer_1', models.CharField(max_length=100, verbose_name='Ответ 1:')),
                ('answer_2', models.CharField(max_length=100, verbose_name='Ответ 2:')),
                ('answer_3', models.CharField(max_length=100, verbose_name='Ответ 3:')),
                ('answer_4', models.CharField(max_length=100, verbose_name='Ответ 4:')),
                ('correct_answer_index', models.PositiveSmallIntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], verbose_name='Прный ответ:')),
            ],
            options={
                'verbose_name': '6. Tест',
                'verbose_name_plural': '6. Тесты',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Введите цитату:')),
                ('author', models.TextField(max_length=50, verbose_name='Автор:')),
            ],
            options={
                'verbose_name': '3. Цитата',
                'verbose_name_plural': '3. Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '8. Раздел',
                'verbose_name_plural': '8. Разделы',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('synonym', models.JSONField()),
            ],
            options={
                'verbose_name': 'Cиноним',
                'verbose_name_plural': 'Синонимы',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
            ],
            options={
                'verbose_name': '1. Слово',
                'verbose_name_plural': '1. Слова',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection', models.CharField(max_length=255, verbose_name='Подраздел')),
                ('section_relate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nza.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': '9. Подраздел',
                'verbose_name_plural': '9. Подразделы',
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Введите тему:')),
                ('description', models.TextField(verbose_name='Введите описание темы:')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nza.example', verbose_name='Пример:')),
                ('subsection', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='nza.subsection', verbose_name='Подраздел')),
                ('test', models.ManyToManyField(to='nza.question', verbose_name='Тест')),
            ],
            options={
                'verbose_name': '2. Грамматика',
                'verbose_name_plural': '2. Грамматика',
            },
        ),
        migrations.CreateModel(
            name='CurrentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nza.quote')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentIdiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nza.idiom')),
            ],
        ),
    ]
