# Generated by Django 4.1.6 on 2023-09-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': '1. Пример', 'verbose_name_plural': '1. Примеры'},
        ),
        migrations.AlterModelOptions(
            name='grammar',
            options={'verbose_name': '4. Грамматика', 'verbose_name_plural': '4. Грамматика'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '5. Tест', 'verbose_name_plural': '5. Тесты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '2. Раздел', 'verbose_name_plural': '2. Разделы'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': '3. Подраздел', 'verbose_name_plural': '3. Подразделы'},
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example',
        ),
        migrations.AddField(
            model_name='grammar',
            name='examples',
            field=models.ManyToManyField(to='nza.example', verbose_name='Примеры'),
        ),
    ]
