# Generated by Django 4.2.3 on 2023-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='obj',
            field=models.CharField(default=2, max_length=100, verbose_name='Слово'),
            preserve_default=False,
        ),
    ]
