# Generated by Django 4.1.6 on 2023-09-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentquote',
            name='quote',
        ),
        migrations.DeleteModel(
            name='CurrentIdiom',
        ),
        migrations.DeleteModel(
            name='CurrentQuote',
        ),
    ]
