# Generated by Django 4.1.6 on 2023-09-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsection', to='nza.section'),
        ),
    ]
