# Generated by Django 4.1.6 on 2023-08-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(verbose_name='Пример: ')),
            ],
        ),
        migrations.AddField(
            model_name='grammar',
            name='example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nza.example', verbose_name='Пример: '),
            preserve_default=False,
        ),
    ]
