# Generated by Django 4.1.6 on 2023-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subsections',
            field=models.ManyToManyField(to='nza.subsection', verbose_name='Подразделы'),
        ),
    ]
