# Generated by Django 4.1.6 on 2023-09-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='nza.subsection', verbose_name='Подраздел'),
            preserve_default=False,
        ),
    ]
