# Generated by Django 4.1.6 on 2023-08-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0002_example_grammar_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
    ]
