# Generated by Django 4.1.6 on 2023-09-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0002_alter_example_options_alter_grammar_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammar',
            old_name='examples',
            new_name='example',
        ),
    ]
