# Generated by Django 4.2.3 on 2023-09-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0002_remove_currentquote_quote_delete_currentidiom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nza.subsection', verbose_name='Подраздел'),
            preserve_default=False,
        ),
    ]
