# Generated by Django 4.1.6 on 2023-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0003_rename_examples_grammar_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='example',
        ),
        migrations.AddField(
            model_name='example',
            name='grammars',
            field=models.ManyToManyField(to='nza.grammar', verbose_name='Связанные грамматики'),
        ),
    ]
