# Generated by Django 4.2.3 on 2023-09-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0003_alter_grammar_subsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='section_relate',
        ),
        migrations.AddField(
            model_name='section',
            name='section_relate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nza.subsection', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
