# Generated by Django 4.1.6 on 2023-09-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0003_alter_section_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nza.subsection', verbose_name='Подраздел'),
        ),
    ]
