# Generated by Django 4.1.6 on 2023-09-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0004_remove_grammar_example_example_grammars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='grammars',
        ),
        migrations.AddField(
            model_name='example',
            name='grammar',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='nza.grammar'),
            preserve_default=False,
        ),
    ]
