# Generated by Django 4.1.6 on 2023-09-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0004_alter_section_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sus', to='nza.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='nza.subsection', verbose_name='Подраздел'),
        ),
    ]
