# Generated by Django 4.2.3 on 2023-09-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0004_remove_subsection_section_relate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_relate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nza.subsection', verbose_name='Раздел'),
        ),
    ]
