# Generated by Django 4.2.3 on 2023-09-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0005_alter_section_section_relate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_relate',
        ),
    ]
