# Generated by Django 4.1.6 on 2023-09-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0005_remove_example_grammars_example_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='example', to='nza.grammar'),
        ),
    ]
