# Generated by Django 4.1.6 on 2023-09-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0005_subsection_section_alter_section_subsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subsection',
        ),
    ]
