# Generated by Django 4.1.6 on 2023-09-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0006_alter_example_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example', to='nza.grammar', verbose_name='Грамматика'),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar', to='nza.subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='nza.grammar', verbose_name='Грамматика'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection', to='nza.section', verbose_name='Раздел'),
        ),
    ]
