# Generated by Django 4.2.3 on 2023-09-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0006_remove_section_section_relate'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nza.section', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
