# Generated by Django 4.1.6 on 2023-09-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0006_remove_section_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsection', to='nza.section'),
        ),
    ]
