# Generated by Django 4.1.6 on 2023-09-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0007_alter_subsection_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antonym',
            options={'verbose_name': '11. Антоним', 'verbose_name_plural': '11. Антонимы'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': '2. Пример', 'verbose_name_plural': '2. Примеры'},
        ),
        migrations.AlterModelOptions(
            name='grammar',
            options={'verbose_name': '5. Грамматика', 'verbose_name_plural': '5. Грамматика'},
        ),
        migrations.AlterModelOptions(
            name='idiom',
            options={'verbose_name': '7. Идиома', 'verbose_name_plural': '7. Идиомы'},
        ),
        migrations.AlterModelOptions(
            name='listening',
            options={'verbose_name': '9. Аудирование', 'verbose_name_plural': '9. Аудирование'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '1. Tест', 'verbose_name_plural': '1. Тесты'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': '8. Цитата', 'verbose_name_plural': '8. Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '3. Раздел', 'verbose_name_plural': '3. Разделы'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': '4. Подраздел', 'verbose_name_plural': '4. Подразделы'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': '10. Cиноним', 'verbose_name_plural': '10. Синонимы'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '6. Слово', 'verbose_name_plural': '6. Слова'},
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example',
        ),
        migrations.AddField(
            model_name='grammar',
            name='example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nza.example', verbose_name='Пример: '),
            preserve_default=False,
        ),
    ]
