# Generated by Django 4.2.3 on 2023-09-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0007_grammar_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nza.subsection', verbose_name='Подраздел'),
            preserve_default=False,
        ),
    ]
