# Generated by Django 4.1.6 on 2023-09-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0007_alter_example_grammar_alter_grammar_subsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': '4. Пример', 'verbose_name_plural': '4. Примеры'},
        ),
        migrations.AlterModelOptions(
            name='grammar',
            options={'verbose_name': '3. Грамматика', 'verbose_name_plural': '3. Грамматика'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '1. Раздел', 'verbose_name_plural': '1. Разделы'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': '2. Подраздел', 'verbose_name_plural': '2. Подразделы'},
        ),
    ]
