# Generated by Django 4.1.6 on 2023-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0008_alter_example_options_alter_grammar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='antonym',
            field=models.CharField(max_length=100),
        ),
    ]
