# Generated by Django 4.1.6 on 2023-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0009_alter_antonym_antonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='antonym',
            field=models.CharField(max_length=100, verbose_name='Антоним'),
        ),
        migrations.AlterField(
            model_name='antonym',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym',
            field=models.CharField(max_length=100, verbose_name='Синоним'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Слово'),
        ),
    ]
