# Generated by Django 4.2.3 on 2023-09-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0009_alter_section_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='nza.subsection', verbose_name='Подраздел'),
        ),
    ]
