# Generated by Django 4.2.3 on 2023-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0010_alter_section_subsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subsection',
        ),
        migrations.AddField(
            model_name='section',
            name='subsections',
            field=models.ManyToManyField(to='nza.subsection', verbose_name='Подразделы'),
        ),
    ]
