# Generated by Django 4.1.6 on 2023-09-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0010_alter_antonym_antonym_alter_antonym_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiom',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Введите идиому:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор:'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Введите цитату:'),
        ),
    ]
