# Generated by Django 4.2.3 on 2023-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0011_remove_section_subsection_section_subsections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='example',
        ),
        migrations.AddField(
            model_name='grammar',
            name='example',
            field=models.ManyToManyField(to='nza.example', verbose_name='Пример:'),
        ),
    ]
