# Generated by Django 4.2.3 on 2023-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0012_remove_grammar_example_grammar_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='subsection',
        ),
    ]
