# Generated by Django 4.2.3 on 2023-09-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0013_remove_grammar_subsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='subsections',
            new_name='subsection',
        ),
    ]
