# Generated by Django 4.2.3 on 2023-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0014_rename_subsections_section_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], verbose_name='Правильный ответ:'),
        ),
    ]
