# Generated by Django 4.2.3 on 2023-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nza', '0015_alter_question_correct_answer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsection',
            field=models.ManyToManyField(related_name='subs', to='nza.subsection', verbose_name='Подразделы'),
        ),
    ]
